server:
  port: 8080

spring:
  application:
    name: customer
  data:
    mongodb:
      uri: mongodb+srv://fardi:fardi@fardicluster.jcch73w.mongodb.net/?retryWrites=true&w=majority
      database: customers
      auto-index-creation: true
  main:
    allow-circular-references: true




logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG







